### PR TITLE
General design suggestions

### PR DESCRIPTION
**Pull request by sshcrack**
This pull requests proposes an example for a Sources API that could be used in v2.0.0. The implementation is not fully done though.
Let me know what you think of this suggestion.

Edit:
I've added a cli tool to build obs and put it in the target dir. In addition to that, I've added some getters and refactored a lot

### CODE REVIEW

**Comment by sshcrack** [comment]
Also, just added a procedural macro and split the library into multiple crates because a procedural macro always needs a separate crate. Furthermore, the obs_source_builder makes it easy to define new source builders

**Review by sshcrack — COMMENTED** [review]
Implemented `game_capture` and `window_capture` so far.  The other packages must be published in order for this update to work.

**Comment by joshprk** [comment]
Hey, sorry for the late reply! My PC is currently broken down. Writing code to streamline making specific sources sounds like a great idea. Take a look at the v0.2.0 branch, it seems like all of the code that you wrote can easily be merged into that branch once its a bit more implemented, but just so we’re on the same page.

Maybe we should use a Discord server, even if it’s small, to communicate? I noticed you are also trying to implement clipping software and I have a lot of the design worked out. Maybe we can collaborate :) My discord name is joshprk if you’d like to talk more

**Comment by sshcrack** [comment]
Alright, will do!

**Comment by sshcrack** [comment]
Didn't want to touch the v0.2.0 branch for now because it is quite a WIP. Is it possible for you to create some simple functions with a todo! macro so I can adapt the sources api?

**Comment by joshprk** [comment]
Yeah, my computer will be up and running in two days so that's when I can do it. I don't think it'll be very different to the current one so I wouldn't worry about what may be on there. It'll just be a lot more cleaner in terms of naming (i.e. removing the Obs prefix from unnecessary stuff) and internals (using traits to properly handle data, etc.). If there are major incompatibilities in the merge, I'll do my best to fix them.

**Comment by sshcrack** [comment]
Okay, alright

**Comment by sshcrack** [comment]
The basic packages should be ready to go, I've already published the cli tool for me to test it and would suggest creating an organization. (also: I've added you on discord)

**Comment by joshprk** [comment]
Hi, I've been really busy recently and haven't been able to keep up. I didn't get the friend request because I accidentally mistyped my Discord username, which is joshuprk. I invited you as a contributor since you seem interested in maintaining the crate.

**Comment by sshcrack** [comment]
Alright first of all thank you, I've sent the friend request to the correct
discord account now and will be migrating the changes I've made to this
repo. I haven't tried yet, am I able to push changes to the libobs crate
now as well?

**Comment by sshcrack** [comment]
Alright, I'm merging so I can work from there on, currently working on preview windows

**Pull request merged**
